---
apiVersion: v1
kind: Service
metadata:
  name: neo-embedding
spec:
  selector:
    app.kubernetes.io/name: neo-embedding
  ports:
    - name: HTTP
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: Bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
