---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  labels:
      app.kubernetes.io/name: llm
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm
  template:
    metadata:
      labels:
          app.kubernetes.io/name: llm
    spec:
      containers:
        - image: localhost:8082/docker-private/llmcpp:cick3fqqoky7d2yb
          name: llm
          ports:
            - name: api
              containerPort: 3000
