version: "3.9"
services:
  postgresql:
    container_name: ailab-pg
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    restart: always
    command: "--work_mem=10MB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/db-data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -tAc 'select 1' -d ailab
      interval: 15s
      timeout: 10s
      retries: 10
