---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
      app.kubernetes.io/name: nexus
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus
  template:
    metadata:
      labels:
          app.kubernetes.io/name: nexus
    spec:
      containers:
        - image: sonatype/nexus3:3.67.1
          name: nexus
          ports:
            - name: ui
              containerPort: 8081
            - name: docker
              containerPort: 8083
          volumeMounts:
          - name: data
            mountPath: /nexus-data
      securityContext:
        fsGroup: 200
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nexus-data