---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app.kubernetes.io/name: nexus
  ports:
    - name: ui
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: docker
      protocol: TCP
      port: 8082
      targetPort: 8082
