apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pmbrull/ailab.git
    targetRevision: main
    path: manifests/apps/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
