---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph
  labels:
      app.kubernetes.io/name: memgraph
  annotations:
    argocd-image-refresh-annotation: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memgraph
  template:
    metadata:
      labels:
          app.kubernetes.io/name: memgraph
    spec:
      containers:
        - image: memgraph/memgraph-mage:1.16-memgraph-2.16
          name: memgraph
          ports:
            - name: http
              containerPort: 7474
            - name: bolt
              containerPort: 7687
          volumeMounts:
            - name: data
              mountPath: /data
      securityContext:
        fsGroup: 200
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: memgraph-data
