---
apiVersion: v1
kind: Service
metadata:
  name: memgraph
spec:
  selector:
    app.kubernetes.io/name: memgraph
  ports:
    - name: http
      protocol: TCP
      port: 7444
      targetPort: 7444
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
