---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer
  labels:
      app.kubernetes.io/name: transformer
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transformer
  template:
    metadata:
      labels:
          app.kubernetes.io/name: transformer
    spec:
      containers:
        - image: localhost:8082/docker-private/transformer:c2kpneawrky7d2yb
          name: transformer
          ports:
            - name: api
              containerPort: 3000
