---
apiVersion: v1
kind: Service
metadata:
  name: transformer
spec:
  selector:
    app.kubernetes.io/name: transformer
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
