neo4j:
  uri: ${NEO4J_URI}
  user: ${NEO4J_USER}
  password: ${NEO4J_PASSWORD}
  database: ${NEO4J_DATABASE}

om:
  uri: ${OM_URI}
  jwt_token: ${OM_JWT_TOKEN}

pg:
  host: ${PG_HOST}
  port: ${PG_PORT}
  user: ${PG_USER}
  password: ${PG_PASSWORD}
  database: ${PG_DATABASE}

llm:
  embedding_model_uri: ${LLM_EMBEDDING_MODEL_URI}
  embedding_model_dim: 1024
  search_strategy: hsnw
  vector_function: cosine_similarity
  table_name: embeddings
